python raft_ds.py \
 --model "deepseek-ai/deepseek-coder-1.3b-base" \
 --data_a "../../data/CSN/python_train.jsonl" \
 --data_b "../../data/RN/RF_train.jsonl" \
 --data_c "../../data/RN/RV_train.jsonl" \
 --output_dir "./checkpoints/RN_ds/" \
 --epochs 3 \
 --batch_size 64 \
 --micro_batch_size 64 \
 --lr 5e-5 \
 --inner_lr 5e-5 \
 --inner_steps 1 \
 >RN_roft_ds.out 2>&1 &